version: '3'

services:
  postgres: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: '123456'
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data